builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    main: ./cmd/wd
nfpms:
  - id: debian
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    replacements:
      Linux: linux
      386: i386
    homepage: https://github.com/reddec/wd
    maintainer: Baryshnikov Aleksandr <owner@reddec.net>
    description: Yet another webhooks daemon
    license: MIT
    bindir: /usr/bin
    formats:
      - deb
    scripts:
      postinstall: "packaging/debian/postinstall.sh"
      preremove: "packaging/debian/preremove.sh"
    empty_folders:
      - /var/webhooks
      - /etc/webhooks
    contents:
      - src: packaging/systemd/webhooks.service
        dst: /etc/systemd/system/webhooks.service

      - src: packaging/systemd/webhooks.env
        dst: /etc/webhooks/webhooks.env
        type: config|noreplace
        file_info:
          mode: 0600
brews:
  - tap:
      owner: reddec
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    folder: Formula
    homepage:  https://github.com/reddec/wd
    description: Yet another webhook daemon
    license: MIT
    test: |
      system "#{bin}/wd --help"
    install: |-
      bin.install "wd"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^build:'
