name: Build and release
on:
  push:
    tags:
      - 'v*'
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: '^1.17'
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          lfs: true
          fetch-depth: 0
      - name: Checkout LFS objects
        run: git lfs checkout

      - name: Pull tag
        run: git fetch --tags
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}